repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        name: fmt
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
-   repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort **/*.py

default_language_version:
    python: python3.7