# Based on https://github.com/cclauss/Travis-CI-Python-on-three-OSes
matrix:
  include:
    - name: "Standard Tests, Parametrized EVM Tests - Python 3.7.1 on Xenial Linux"
      language: python
      python: 3.7
      dist: xenial
      sudo: true
      install:
        - sudo add-apt-repository -y ppa:ethereum/ethereum
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get update
        - sudo apt-get install -y python3.7-dev python3.7-tk npm solc
        - npm -g install ganache-cli
        - python -m pip install -r requirements-dev.txt
      script: tox -e py37,evmtests
    - name: "Standard Tests, Linting, Docs - Python 3.6.8 on Xenial Linux"
      language: python
      python: 3.6
      dist: xenial
      sudo: true
      install:
        - sudo add-apt-repository -y ppa:ethereum/ethereum
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get update
        - sudo apt-get install -y python3.6-dev python3.6-tk npm solc
        - npm -g install ganache-cli
        - python -m pip install -r requirements-dev.txt
      script: tox -e lint,doctest,py36
    - name: "Standard Tests - Python 3.7.3 on Windows"
      os: windows
      language: node_js
      node_js: '10'
      install:
        - npm -g install ganache-cli
        - choco install python
        - python -m pip install --upgrade pip
        - python -m pip install -r requirements-dev.txt
        - python setup.py install
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      script: python -m pytest tests/ --cov=brownie/ -p no:pytest-brownie
    - name: "Brownie Mix Tests - Python 3.6.8 on Xenial Linux"
      language: python
      python: 3.6
      dist: xenial
      sudo: true
      install:
        - sudo add-apt-repository -y ppa:ethereum/ethereum
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get update
        - sudo apt-get install -y python3.6-dev python3.6-tk npm solc
        - npm -g install ganache-cli
        - python -m pip install -r requirements-dev.txt
      script: tox -e mixtests

env:
  global: COVERALLS_PARALLEL=true
after_success: python -m coveralls
notifications:
  email: false
  webhooks: https://coveralls.io/webhook
